### ISSUE TITLE
 DeprecationWarning: Testing an element's truth value

### ISSUE THREAD

**Issue by QINZHAOYU** [JakubAndrysek/MkDoxy#100]
Thank you very much for the tool, perfect solution to my need to generate documentation for C++ projects!

While i upgrade python from 3.9 to 3.12.2, with mkdoxy 1.2.0, there is a warning appeared, as below: 

INFO    -  Building documentation...
INFO    -  Cleaning site directory
INFO    -  Start plugin MkDoxy
INFO    -  -> Start project 'models'
INFO    -    -> generating Doxygen files
INFO    -  DeprecationWarning: Testing an element's truth value will raise an exception in future versions.  Use specific 'len(elem)' or
           'elem is not None' test instead.
             File "D:\miniconda3\envs\oasis\Lib\site-packages\mkdoxy\node.py", line 736, in brief
               return self._brief.md()
             File "D:\miniconda3\envs\oasis\Lib\site-packages\mkdoxy\property.py", line 38, in md
               if not briefdescription:

I'm not sure if it's the python version that causes it,  just as a feedback.

**Comment by JakubAndrysek** [comment]
Thank you for finding the warning, I will look at it.
