### ISSUE TITLE
What is policy for contributions?

### ISSUE THREAD

**Issue by kamorrissey** [JakubAndrysek/MkDoxy#55]
What is your policy for contributing? I would like to expand `src-dirs:` in mkdocs.yml config to accept glob patterns, including recursive. Would you mind adding a CONTRIBUTING.md?

**Comment by JakubAndrysek** [comment]
Thank you for your request. 
I'm trying to figure out what do you want to change.
`src-dirs` accept any string that you want. This input is directly passed into Doxygen `INPUT` parameter. Together with `RECURSIVE = YES` is possible to input multiple directories. Then using the `FILE_PATTERNS = *.c *.cpp *.h` argument is possible to limit including files.

I'm working on better documentation that will include this necessary information for future developers.

I didn't have CONTRIBUTING.md right now, but I will add it in the nearest future. I am new to open-source contributions. If you have some recommendations on how to improve this project, please let me know.

**Comment by kamorrissey** [comment]
We have a case where we would like to use the line like

src-dirs: 'src/**/include/public src/**/include/unpublished'

to yield over a dozen directories instead of manually listing them.

sent from my mobile device
Karen A Morrissey
Author, Fisher King: Percival's Descent
***@***.***
karenamorrissey.blogspot.com
720-308-4368 mobile
