### ISSUE TITLE
`ruamel.yaml` missing from runtime dependencies

### ISSUE THREAD

**Issue by tasansal** [JakubAndrysek/MkDoxy#70]
Hi, came here after `doxybook2` got archived! Your project looks very promising.

I was just trying to use it an realized `ruamel` YAML is a dev dependency but not a runtime dependency; which fails if just pip installed.

To replicate:
1. `pip install mkdoxy`
2. `pip install mkdocs`
3. Configure mkdocs to use `mkdoxy`
4. Run `mkdocs build`

Traceback:
```python
File "/Users/.../.venv/lib/python3.11/site-packages/mkdoxy/utils.py", line 5, in <module>
    from ruamel.yaml import YAML
ModuleNotFoundError: No module named 'ruamel'
```

I can make a PR if needed.

**Comment by asherban** [comment]
I suggest instead of adding ruamel as a dependency, switching to PyYAML which is imported by mkdocs.

**Comment by tasansal** [comment]
I agree, maybe if I have some time I can modify my PR. But let’s see what @JakubAndrysek says.

**Comment by JakubAndrysek** [comment]
Yes, I agree.
Could you please create the PR with PyYAML.

Thanks
