### ISSUE TITLE
Using doxygen config file

### ISSUE THREAD

**Issue by modkin** [JakubAndrysek/MkDoxy#93]
Hello,

is it possible to use an existing doxygen config file instead of writing all doxygen options into the `mkdocs.yml` file?

I tried using the `@INCLUDE` tag but the `@` seams to break the parser for the `mkdocs.yml` file.

Thanks in advance

**Comment by NPotvin** [comment]
Hi,
I managed to use a Doxyfile by using `\@INCLUDE: Path/To/Doxyfile`
but not all features of doxygen seem to work (I noticed the inheritance diagram was missing, while present in the doc generated by standalone doxygen)

**Comment by JakubAndrysek** [comment]
Implemented, please, look at the documentation: https://mkdoxy.kubaandrysek.cz/usage/advanced/
